name: Sync manifest on push to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FUSEKI_URL: ${{ secrets.FUSEKI_URL }}
      FUSEKI_USERNAME: ${{ secrets.FUSEKI_USERNAME }}
      FUSEKI_PASSWORD: ${{ secrets.FUSEKI_PASSWORD }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      - name: Run sync
        run: uv run sync.py
