name: Validate manifest on PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install prezmanifest
        run: uv tool install prezmanifest
      - name: Validate manifest
        run: pm validate manifest.ttl
